// @generated by protobuf-ts 2.9.4 with parameter optimize_code_size
// @generated from protobuf file "service.proto" (syntax proto3)
// tslint:disable
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message Void
 */
export interface Void {
}
/**
 * @generated from protobuf message Weather
 */
export interface Weather {
    /**
     * @generated from protobuf field: string weather = 1;
     */
    weather: string;
}
// @generated message type with reflection information, may provide speed optimized methods
class Void$Type extends MessageType<Void> {
    constructor() {
        super("Void", []);
    }
}
/**
 * @generated MessageType for protobuf message Void
 */
export const Void = new Void$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Weather$Type extends MessageType<Weather> {
    constructor() {
        super("Weather", [
            { no: 1, name: "weather", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message Weather
 */
export const Weather = new Weather$Type();
/**
 * @generated ServiceType for protobuf service WeatherService
 */
export const WeatherService = new ServiceType("WeatherService", [
    { name: "GetWeather", options: {}, I: Void, O: Weather }
]);
