// @generated by protobuf-ts 2.9.4 with parameter optimize_code_size
// @generated from protobuf file "service.proto" (syntax proto3)
// tslint:disable
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message Nekaj
 */
export interface Nekaj {
    /**
     * @generated from protobuf field: int32 helo = 1;
     */
    helo: number;
}
// @generated message type with reflection information, may provide speed optimized methods
class Nekaj$Type extends MessageType<Nekaj> {
    constructor() {
        super("Nekaj", [
            { no: 1, name: "helo", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message Nekaj
 */
export const Nekaj = new Nekaj$Type();
/**
 * @generated ServiceType for protobuf service PralnicaService
 */
export const PralnicaService = new ServiceType("PralnicaService", [
    { name: "Hello", options: {}, I: Nekaj, O: Nekaj }
]);
