// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package pralnicaDb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Auth struct {
	ID           int32
	UserUuid     pgtype.UUID
	PasswordHash string
	LastLogin    pgtype.Timestamp
	CreatedAt    pgtype.Timestamp
	UpdatedAt    pgtype.Timestamp
}

type Reservation struct {
	ID     int32
	Uuid   pgtype.UUID
	Date   pgtype.Date
	Termin int32
	Washer int32
}

type User struct {
	Uuid      pgtype.UUID
	Phone     string
	Name      string
	Surname   string
	Room      int32
	Email     string
	Disabled  bool
	Confirmed bool
	Role      string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}
