package docs

import (
	"errors"
	"log"
	"os"

	"github.com/go-chi/chi/v5"
	"github.com/go-chi/docgen"
)

func WriteDocs(r chi.Router) {
	docgen.PrintRoutes(r)

	// Create a new `routes.md` file.
	if err := os.Remove("./docs/routes.md"); err != nil && !errors.Is(err, os.ErrNotExist) {
		log.Fatal(err)
	}
	f, err := os.Create("./docs/routes.md")

	if err != nil {
		log.Fatal(err)
	}

	defer f.Close()

	text := docgen.MarkdownRoutesDoc(r, docgen.MarkdownOpts{ // Here, `r` is the main router.
		ForceRelativeLinks: true, // Without this, you will not see any links to the source code in the Markdown file on your local machine.
		Intro:              "Welcome to the documentation for the RESTful API.",
	})

	// Write the Markdown generated by `docgen` to the `routes.md` file.
	if _, err = f.Write([]byte(text)); err != nil {
		log.Fatal(err)
	}
}
